name: {{{name}}}
description: "{{{description}}}"
{{#repository}}repository: "{{{repository}}}"{{/repository}}
{{#homepage}}homepage: "{{{homepage}}}"{{/homepage}}
version: {{version}}
publish_to: none

# dart pub global activate derry
scripts:
  {{#hasFlavors}}flavors: flutter pub run flutter_flavorizr{{/hasFlavors}}
  {{^dart}}regenerate_goldens: flutter test --update-goldens --tags=golden{{/dart}}
  gen_build: {{#dart}}dart{{/dart}}{{^dart}}flutter{{/dart}} pub run build_runner build --delete-conflicting-outputs
  gen_watch: {{#dart}}dart{{/dart}}{{^dart}}flutter{{/dart}} pub run build_runner watch --delete-conflicting-output

environment:
  sdk: ">=2.17.0 <4.0.0"
  {{^dart}}flutter: ">=3.0.0"{{/dart}}

dependencies:
  {{^dart}}flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg:
  auth_buttons:
  flex_color_scheme:
  flutter_riverpod:
  go_router:
  google_fonts:
  handy_window:
  phone_form_field:
  cupertino_icons:
  accessibility_tools:
  flutter_data: {{/dart}}
  collection:
  dio:
  freezed_annotation:
  intl:
  json_annotation:
  json_api:
  shared_preferences:
  path_provider:
  riverpod_annotation:
  state_notifier:
  universal_io:
  upgrader:
  platform:
  uuid:
  {{#dart}}riverpod: {{/dart}}

dev_dependencies:
  mocktail:
  test:
  build_runner: {{^dart}}
  bdd_widget_test:
  go_router_builder:
  {{#hasFlavors}}flutter_flavorizr:{{/hasFlavors}}
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  alchemist:
  flutter_goldens:
    sdk: flutter
  integration_test:
    sdk: flutter{{/dart}}
  spec:
  freezed:
  icons_launcher:
  json_serializable:
  riverpod_generator:
{{^dart}}
flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
#  generate: true
  assets:
    - assets/
    - assets/image/
    - assets/image/vector/
    - assets/image/raster/
    - assets/multimedia/
    - assets/multimedia/audio/
    - assets/multimedia/video/
    - assets/pdf/
    - assets/font/
    - assets/color/
    - assets/txt/
    - assets/animation/
    - assets/animation/rive/
    - assets/animation/lottie/
#  fonts:
#    - family: Comfortaa
#      fonts:
#        - asset: assets/fonts/comfortaa.ttf
{{/dart}}
{{#hasFlavors}}
flavorizr:
  ide: {{IDE}}
  instructions: [
      assets:download,
      assets:extract,
      assets:clean,
      android:buildGradle,
      android:androidManifest,
      android:icons,
      ios:icons,
      ios:plist
  ]
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    {{#flavors}}{{.}}:
      app:
        name: {{.}}
      android:
        applicationId: "{{org}}.{{{name}}}"
      ios:
        bundleId: "{{org}}.{{{name}}}"
  {{/flavors}}
{{/hasFlavors}}
#{{^dart}}flutter_gen:
#  output: packages/common/gen/
#  line_length: 80
#  gen_for_package: true
#  integrations:
#    flutter_svg: true
#  assets:
#    enabled: true
#  fonts:
#    enabled: true
#  colors:
#    enabled: true
#    inputs:
#      - assets/color/colors.xml{{/dart}}
